from setuptools import setup

setup(
    name='shodan-mongodb',
    version='0.1',
    packages=['venv.lib.python3.7.site-packages.PIL', 'venv.lib.python3.7.site-packages.pip',
              'venv.lib.python3.7.site-packages.pip._vendor', 'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.bson',
              'venv.lib.python3.7.site-packages.idna', 'venv.lib.python3.7.site-packages.click',
              'venv.lib.python3.7.site-packages.numpy', 'venv.lib.python3.7.site-packages.numpy.ma',
              'venv.lib.python3.7.site-packages.numpy.ma.tests', 'venv.lib.python3.7.site-packages.numpy.doc',
              'venv.lib.python3.7.site-packages.numpy.fft', 'venv.lib.python3.7.site-packages.numpy.fft.tests',
              'venv.lib.python3.7.site-packages.numpy.lib', 'venv.lib.python3.7.site-packages.numpy.lib.tests',
              'venv.lib.python3.7.site-packages.numpy.core', 'venv.lib.python3.7.site-packages.numpy.core.tests',
              'venv.lib.python3.7.site-packages.numpy.f2py', 'venv.lib.python3.7.site-packages.numpy.f2py.tests',
              'venv.lib.python3.7.site-packages.numpy.tests', 'venv.lib.python3.7.site-packages.numpy.compat',
              'venv.lib.python3.7.site-packages.numpy.compat.tests', 'venv.lib.python3.7.site-packages.numpy.linalg',
              'venv.lib.python3.7.site-packages.numpy.linalg.tests', 'venv.lib.python3.7.site-packages.numpy.random',
              'venv.lib.python3.7.site-packages.numpy.random.tests', 'venv.lib.python3.7.site-packages.numpy.testing',
              'venv.lib.python3.7.site-packages.numpy.testing.tests',
              'venv.lib.python3.7.site-packages.numpy.testing._private',
              'venv.lib.python3.7.site-packages.numpy.distutils',
              'venv.lib.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib.python3.7.site-packages.numpy.distutils.command',
              'venv.lib.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.7.site-packages.numpy.matrixlib',
              'venv.lib.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.7.site-packages.numpy.polynomial',
              'venv.lib.python3.7.site-packages.numpy.polynomial.tests', 'venv.lib.python3.7.site-packages.gridfs',
              'venv.lib.python3.7.site-packages.shodan', 'venv.lib.python3.7.site-packages.shodan.cli',
              'venv.lib.python3.7.site-packages.shodan.cli.converter', 'venv.lib.python3.7.site-packages.certifi',
              'venv.lib.python3.7.site-packages.chardet', 'venv.lib.python3.7.site-packages.chardet.cli',
              'venv.lib.python3.7.site-packages.pymongo', 'venv.lib.python3.7.site-packages.urllib3',
              'venv.lib.python3.7.site-packages.urllib3.util', 'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.colorama', 'venv.lib.python3.7.site-packages.dateutil',
              'venv.lib.python3.7.site-packages.dateutil.tz', 'venv.lib.python3.7.site-packages.dateutil.parser',
              'venv.lib.python3.7.site-packages.dateutil.zoneinfo', 'venv.lib.python3.7.site-packages.requests',
              'venv.lib.python3.7.site-packages.wordcloud', 'venv.lib.python3.7.site-packages.matplotlib',
              'venv.lib.python3.7.site-packages.matplotlib.tri', 'venv.lib.python3.7.site-packages.matplotlib.axes',
              'venv.lib.python3.7.site-packages.matplotlib.cbook', 'venv.lib.python3.7.site-packages.matplotlib.style',
              'venv.lib.python3.7.site-packages.matplotlib.tests', 'venv.lib.python3.7.site-packages.matplotlib.compat',
              'venv.lib.python3.7.site-packages.matplotlib.testing',
              'venv.lib.python3.7.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.7.site-packages.matplotlib.backends',
              'venv.lib.python3.7.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.7.site-packages.matplotlib.projections', 'venv.lib.python3.7.site-packages.xlsxwriter',
              'venv.lib.python3.7.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.7.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axisartist',
              'venv.lib.python3.7.site-packages.click_plugins'],
    url='GPL',
    license='',
    author='Ahmet Ozturk',
    author_email='oahmet@gmail.com',
    description='A simple tool search unauthenticated MongoDB instances on Shodan.io and create some graphs'
)
